sudo: false
services:
  - xvfb
language: node_js
node_js:
- 6
- lts/*

env:
  global:
    - CXX=g++-4.8
  matrix:
  - BROWSER=chrome  BVER=stable
  - BROWSER=chrome  BVER=beta
  - BROWSER=chrome  BVER=unstable
  - BROWSER=firefox BVER=stable
  - BROWSER=firefox BVER=beta
  - BROWSER=firefox BVER=nightly

matrix:
  fast_finish: true

  allowed_failures:
    - env: BROWSER=chrome  BVER=unstable
    - env: BROWSER=firefox BVER=nightly

before_script:
  - ./node_modules/travis-multirunner/setup.sh

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done || true

notifications:
  email:
  - nathan.oehlman@coviu.com
  irc: irc.freenode.org#rtc.io

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
